runtime: python
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/testproject/index.html
    upload: dist/testproject/index.js
  - url: /
    static_dir: dist/testproject

skip_files:
  - node_mosules/
  - src/