
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install','--legacy-peer-deps']
  
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run','build']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app','deploy']